[package]
name = "blogger"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = { version = "0.5.0-rc.1", features = [] }
tokio = { version = "1", features = ["full"] }
rusqlite = { version = "0.25", features = ["chrono"] }
chrono = "0.4"

[dependencies.rocket_sync_db_pools]
version = "0.1.0-rc.1"
default-features = false 
features = ["sqlite_pool"]