base_url = "https://evan-brass.github.io"

title = "Evan Brass"
description = "Mediocre content about life and my technical interests."

compile_sass = false
generate_feed = true
build_search_index = false
sort_by = "date"

taxonomies = [
	{ name = "tags", feed = true }
]
# Try to get forestry to use toml frontmatter
metaDataFormat = "toml"

[markdown]
highlight_code = true
# highlight_theme = "solarized-light"
# highlight_theme = "css"
# highlighting_themes_css = [
# 	{ theme = "solarized-dark", filename = "highlight-dark.css" },
# 	{ theme = "solarized-light", filename = "highlight-light.css" }
# ]

[extra]
# publisher = "Evan Brass"
author = "Evan Brass"
social = [
	{ name = "Twitter", url = "https://twitter.com/evan_brass" },
	{ name = "GitHub", url = "https://github.com/evan-brass" },
	# { name = "LinkedIn", url = "https://www.linkedin.com/in/evan-brass-a26260a9/" }
]
