base_url = "https://evan-brass.github.io"

title = "Evan Brass"
description = "Mediocre content about life and my technical interests."

compile_sass = false
highlight_code = true
generate_feed = true
build_search_index = false
sort_by = "date"
# highlight_theme = "monokai-var"

taxonomies = [
	{ name = "tags", feed = true }
]

[extra]
