base_url = "https://evan-brass.github.io"

title = "Evan Brass"
description = "Mediocre content about life and my technical interests."

compile_sass = false
highlight_code = true
generate_feed = true
build_search_index = false
sort_by = "date"
# highlight_theme = "monokai-var"

taxonomies = [
	{ name = "tags", feed = true }
]

[extra]
social = [
	{ name = "Twitter", url = "https://twitter.com/evan_brass" },
	{ name = "GitHub", url = "https://github.com/evan-brass" },
	# { name = "LinkedIn", url = "https://www.linkedin.com/in/evan-brass-a26260a9/" }
]
